#!/bin/bash
# Nexora server setup script
# Run from the repo root: bash server_setup.sh

set -e

echo ""
echo "======================================"
echo "  Nexora Server Setup"
echo "======================================"
echo ""

# ── Generate secrets ──────────────────────────────────────────
API_SECRET=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
DB_PASS=$(openssl rand -hex 16)
WEBHOOK_SECRET=$(openssl rand -hex 16)

echo "✓ Generated random secrets"

# ── Prompt for required values ────────────────────────────────
echo ""
echo "Enter your API keys (press Enter to skip and fill in later):"
echo ""

read -p "  Claude API key (sk-ant-...): " CLAUDE_KEY
read -p "  OpenAI API key (sk-...):     " OPENAI_KEY
read -p "  Admin email:                 " ADMIN_EMAIL
read -p "  Admin password:              " ADMIN_PASS
read -p "  n8n password:                " N8N_PASS

ADMIN_EMAIL=${ADMIN_EMAIL:-admin@nexora.local}
ADMIN_PASS=${ADMIN_PASS:-$(openssl rand -hex 8)}
N8N_PASS=${N8N_PASS:-$(openssl rand -hex 8)}

# ── Write .env ────────────────────────────────────────────────
cat > .env <<EOF
# Generated by server_setup.sh

# AI Provider Keys
CLAUDE_API_KEY=${CLAUDE_KEY}
OPENAI_API_KEY=${OPENAI_KEY}
GEMINI_API_KEY=
DEFAULT_AI_PROVIDER=claude

# Database
DATABASE_URL=postgresql://nexora:${DB_PASS}@postgres:5432/nexora
DB_PASSWORD=${DB_PASS}

# Security
API_SECRET_KEY=${API_SECRET}
JWT_SECRET_KEY=${JWT_SECRET}
WEBHOOK_SECRET=${WEBHOOK_SECRET}

# Admin account (created on first boot)
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASS}
ADMIN_FIRST_NAME=Admin

# n8n
N8N_USER=admin
N8N_PASSWORD=${N8N_PASS}
N8N_HOST=localhost
N8N_PROTOCOL=http
N8N_WEBHOOK_URL=http://localhost:5678/

# n8n internal webhooks
N8N_NEW_LEAD_WEBHOOK=http://n8n:5678/webhook/crm-new-lead
N8N_APPOINTMENT_WEBHOOK=http://n8n:5678/webhook/appointment-confirmed

# WhatsApp (fill in after Meta app setup)
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_ACCESS_TOKEN=
WHATSAPP_VERIFY_TOKEN=${WEBHOOK_SECRET}
WHATSAPP_CLIENT_ID=
WHATSAPP_BUSINESS_NAME=Nexora

# CRM (fill in later)
HUBSPOT_API_KEY=
ZOHO_CLIENT_ID=
ZOHO_CLIENT_SECRET=
ZOHO_REFRESH_TOKEN=

# Google Calendar (fill in later)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REFRESH_TOKEN=
GOOGLE_CALENDAR_ID=primary
GOOGLE_TIMEZONE=Asia/Kolkata

# Server
TIMEZONE=Asia/Kolkata
EOF

echo "✓ .env file created"

# ── Start Docker stack ────────────────────────────────────────
echo ""
echo "Starting production Docker stack..."
docker compose -f docker-compose.prod.yml up -d --build

# ── Wait for health check ─────────────────────────────────────
echo ""
echo "Waiting for backend to be ready..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:8000/health > /dev/null 2>&1; then
    echo "✓ Backend is healthy"
    break
  fi
  echo "  ... waiting ($i/30)"
  sleep 3
done

# ── Final status ──────────────────────────────────────────────
echo ""
echo "======================================"
echo "  Container Status"
echo "======================================"
docker compose -f docker-compose.prod.yml ps

echo ""
echo "======================================"
echo "  Setup Complete"
echo "======================================"
echo ""
echo "  Backend API:  http://localhost:8000"
echo "  n8n:          http://localhost:5678"
echo "  n8n login:    admin / ${N8N_PASS}"
echo "  Dashboard:    ${ADMIN_EMAIL} / ${ADMIN_PASS}"
echo ""
echo "  Next steps:"
echo "  1. Set up Cloudflare Tunnel (see sops/server_deployment.md Part 5)"
echo "  2. Update Vercel NEXT_PUBLIC_API_URL to your public API URL"
echo "  3. Fill in WhatsApp/HubSpot/Zoho/Google creds via the dashboard"
echo ""
