#!/bin/bash
# Nexora server setup — fully automated, no prompts
# Run from repo root: bash server_setup.sh

set -e

echo ""
echo "======================================"
echo "  Nexora Server Setup"
echo "======================================"
echo ""

# ── Generate strong secrets ───────────────────────────────────
API_SECRET=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
DB_PASS=$(openssl rand -hex 16)
WEBHOOK_SECRET=$(openssl rand -hex 16)
N8N_PASS=$(openssl rand -hex 8)

echo "✓ Secrets generated"

# ── Write .env ────────────────────────────────────────────────
cat > .env <<EOF
# Generated by server_setup.sh — $(date)

# AI Provider Keys
CLAUDE_API_KEY=REPLACE_CLAUDE_KEY
OPENAI_API_KEY=REPLACE_OPENAI_KEY
GEMINI_API_KEY=REPLACE_GEMINI_KEY
DEFAULT_AI_PROVIDER=claude

# Database
DATABASE_URL=postgresql://nexora:${DB_PASS}@postgres:5432/nexora
DB_PASSWORD=${DB_PASS}

# Security
API_SECRET_KEY=${API_SECRET}
JWT_SECRET_KEY=${JWT_SECRET}
WEBHOOK_SECRET=${WEBHOOK_SECRET}

# Admin account (created on first boot)
ADMIN_EMAIL=sodhi.398@gmail.com
ADMIN_PASSWORD=Changeme123!
ADMIN_FIRST_NAME=Devin

# n8n
N8N_USER=admin
N8N_PASSWORD=${N8N_PASS}
N8N_HOST=localhost
N8N_PROTOCOL=http
N8N_WEBHOOK_URL=http://localhost:5678/
N8N_NEW_LEAD_WEBHOOK=http://n8n:5678/webhook/crm-new-lead
N8N_APPOINTMENT_WEBHOOK=http://n8n:5678/webhook/appointment-confirmed

# WhatsApp (fill in after Meta app setup)
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_ACCESS_TOKEN=
WHATSAPP_VERIFY_TOKEN=nexora-verify-2026
WHATSAPP_CLIENT_ID=
WHATSAPP_BUSINESS_NAME=Nexora

# CRM (fill in later via dashboard)
HUBSPOT_API_KEY=
ZOHO_CLIENT_ID=
ZOHO_CLIENT_SECRET=
ZOHO_REFRESH_TOKEN=

# Google Calendar (fill in later via dashboard)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REFRESH_TOKEN=
GOOGLE_CALENDAR_ID=primary
GOOGLE_TIMEZONE=Asia/Kolkata

# Server
TIMEZONE=Asia/Kolkata
EOF

echo "✓ .env created"

# ── Inject API keys ───────────────────────────────────────────
# Keys are passed via environment variables to keep them out of the script
if [ -n "$CLAUDE_KEY" ]; then
  sed -i "s|REPLACE_CLAUDE_KEY|${CLAUDE_KEY}|" .env
  echo "✓ Claude API key set"
fi
if [ -n "$OPENAI_KEY" ]; then
  sed -i "s|REPLACE_OPENAI_KEY|${OPENAI_KEY}|" .env
  echo "✓ OpenAI API key set"
fi
if [ -n "$GEMINI_KEY" ]; then
  sed -i "s|REPLACE_GEMINI_KEY|${GEMINI_KEY}|" .env
  echo "✓ Gemini API key set"
fi

# ── Start Docker stack ────────────────────────────────────────
echo ""
echo "Building and starting Docker stack..."
docker compose -f docker-compose.prod.yml up -d --build

# ── Wait for health check ─────────────────────────────────────
echo ""
echo "Waiting for backend to be ready..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:8000/health > /dev/null 2>&1; then
    echo "✓ Backend is healthy"
    break
  fi
  echo "  ... waiting ($i/30)"
  sleep 3
done

# ── Final status ──────────────────────────────────────────────
echo ""
echo "======================================"
echo "  Container Status"
echo "======================================"
docker compose -f docker-compose.prod.yml ps

echo ""
echo "======================================"
echo "  Setup Complete"
echo "======================================"
echo ""
echo "  Backend API : http://localhost:8000/health"
echo "  n8n         : http://localhost:5678"
echo "  n8n login   : admin / ${N8N_PASS}"
echo "  Dashboard   : sodhi.398@gmail.com / Changeme123!"
echo ""
echo "  Next: set up Cloudflare Tunnel for public access"
echo "  See: sops/server_deployment.md Part 5"
echo ""
