"""add whatsapp_conversations table

Revision ID: 72940979d955
Revises: b023c3d34530
Create Date: 2026-05-13 22:11:14.960689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72940979d955'
down_revision: Union[str, Sequence[str], None] = 'b023c3d34530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('last_reply', sa.Text(), nullable=True),
    sa.Column('last_intent', sa.String(), nullable=True),
    sa.Column('message_count', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_conversations_phone_number'), 'whatsapp_conversations', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_conversations_phone_number'), table_name='whatsapp_conversations')
    op.drop_table('whatsapp_conversations')
    # ### end Alembic commands ###
